"""v4

Revision ID: 02cf380ec00d
Revises: b568dcbd28d3
Create Date: 2025-07-10 11:46:21.828252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02cf380ec00d'
down_revision: Union[str, None] = 'b568dcbd28d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userorglink', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('userorglink', sa.Column('super', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userorglink', 'super')
    op.drop_column('userorglink', 'disabled')
    # ### end Alembic commands ###
