"""v3

Revision ID: 6f5e7126f886
Revises: 3648d22d899a
Create Date: 2025-07-07 14:25:49.512385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f5e7126f886'
down_revision: Union[str, None] = '3648d22d899a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userinfo', sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userinfo', sa.Column('contactNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'contactNumber')
    op.drop_column('userinfo', 'lastName')
    op.drop_column('userinfo', 'firstName')
    # ### end Alembic commands ###
