"""v3

Revision ID: 7f2897c216c5
Revises: 86d7a9cb8d24
Create Date: 2025-07-28 14:55:05.668061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f2897c216c5'
down_revision: Union[str, None] = '86d7a9cb8d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('menu', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('menu', sa.Column('href', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_menu_name', table_name='menu')
    op.create_index(op.f('ix_menu_label'), 'menu', ['label'], unique=False)
    op.drop_column('menu', 'name')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_menu_label'), table_name='menu')
    op.create_index('ix_menu_name', 'menu', ['name'], unique=False)
    op.drop_column('menu', 'href')
    op.drop_column('menu', 'icon')
    op.drop_column('menu', 'label')
    # ### end Alembic commands ###
