"""v2

Revision ID: 86d7a9cb8d24
Revises: 03430cd96632
Create Date: 2025-07-14 15:02:08.624770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86d7a9cb8d24'
down_revision: Union[str, None] = '03430cd96632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_action_name', table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='action_pkey')
    )
    op.create_index('ix_action_name', 'action', ['name'], unique=False)
    # ### end Alembic commands ###
