"""v2

Revision ID: b568dcbd28d3
Revises: c6eb8b1c7a5a
Create Date: 2025-07-10 11:25:22.879738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b568dcbd28d3'
down_revision: Union[str, None] = 'c6eb8b1c7a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('role', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'updatedAt')
    op.drop_column('role', 'createdAt')
    # ### end Alembic commands ###
