"""v3

Revision ID: d047aff8f6e1
Revises: 02cf380ec00d
Create Date: 2025-07-10 11:48:19.704267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd047aff8f6e1'
down_revision: Union[str, None] = '02cf380ec00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userorglink', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('userorglink', 'super',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userorglink', 'super',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('userorglink', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
